// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test-TPS-login-admin-password-CV', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test-TPS-login-admin-password-CV', async function() {
    await driver.get("http://localhost:1111/admin/login")
    await driver.manage().window().setRect({ width: 609, height: 728 })
    await driver.findElement(By.id("email")).sendKeys("admin@admin.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("admin")
    await driver.findElement(By.id("loginForm")).click()
    assert(await driver.findElement(By.css("h2")).getText() == "Dashboard")
  })
})

describe('Test-TPS-login-admin-password-CI-1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test-TPS-login-admin-password-CI-1', async function() {
    await driver.get("http://localhost:1111/admin/login")
    await driver.manage().window().setRect({ width: 609, height: 728 })
    await driver.findElement(By.id("email")).sendKeys("admin@admin.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("\"\"")
    await driver.findElement(By.id("loginForm")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Access denied. Check password and try again.")
  })
})

describe('Test-TPS-login-admin-password-CI-2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test-TPS-login-admin-password-CI-2', async function() {
    await driver.get("http://localhost:1111/admin/login")
    await driver.manage().window().setRect({ width: 609, height: 728 })
    await driver.findElement(By.id("email")).sendKeys("admin@admin.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("adMIN")
    await driver.findElement(By.id("loginForm")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Access denied. Check password and try again.")
    assert(await driver.findElement(By.id("notify_message")).getText() == "Access denied. Check password and try again.")
  })
})