// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create-Menu-menu-CV', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create-Menu-menu-CV', async function() {
    await driver.get("http://localhost:1111/admin/settings/menu")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("newNavMenu")).click()
    await driver.findElement(By.id("newNavMenu")).sendKeys("Facebook")
    await driver.findElement(By.id("newNavLink")).click()
    await driver.findElement(By.id("newNavLink")).sendKeys("https://www.facebook.com/expresscart2021")
    await driver.findElement(By.id("settings-menu-new")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Menu created successfully.")
  })
})

describe('Create-Menu-menu-CI-1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create-Menu-menu-CI-1', async function() {
    await driver.get("http://localhost:1111/admin/settings/menu")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("newNavMenu")).click()
    await driver.findElement(By.id("newNavMenu")).sendKeys("\"\"")
    await driver.findElement(By.id("newNavLink")).click()
    await driver.findElement(By.id("newNavLink")).sendKeys("https://www.facebook.com/expresscart2021")
    await driver.findElement(By.id("settings-menu-new")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Menu created successfully.")
    assert(await driver.findElement(By.id("notify_message")).getText() == "Menu created successfully.")
  })
})

describe('Create-Menu-menu-CI-2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create-Menu-menu-CI-2', async function() {
    await driver.get("http://localhost:1111/admin/settings/menu")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("newNavMenu")).click()
    await driver.findElement(By.id("newNavMenu")).sendKeys("123456789")
    await driver.findElement(By.id("newNavLink")).click()
    await driver.findElement(By.id("newNavLink")).sendKeys("https://www.facebook.com/expresscart2021")
    await driver.findElement(By.id("settings-menu-new")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Menu created successfully.")
    assert(await driver.findElement(By.id("notify_message")).getText() == "Menu created successfully.")
    assert(await driver.findElement(By.id("notify_message")).getText() == "Menu created successfully.")
  })
})