// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('review-title-CV', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('review-title-CV', async function() {
    await driver.get("http://localhost:1111/")
    await driver.manage().window().setRect({ width: 757, height: 728 })
    await driver.findElement(By.css(".col-6:nth-child(1) .img-fluid")).click()
    await driver.findElement(By.id("add-review")).click()
    await driver.findElement(By.id("review-title")).click()
    await driver.findElement(By.id("review-title")).sendKeys("Producto nuevo")
    await driver.findElement(By.id("review-description")).click()
    await driver.findElement(By.id("review-description")).sendKeys("Producto en excelente estado. ")
    await driver.findElement(By.id("review-rating")).click()
    await driver.findElement(By.id("review-rating")).sendKeys("5")
    await driver.findElement(By.id("addReview")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Review successfully submitted")
  })
})

describe('review-title-CI-1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('review-title-CI-1', async function() {
    await driver.get("http://localhost:1111/")
    await driver.manage().window().setRect({ width: 757, height: 728 })
    await driver.findElement(By.css(".col-6:nth-child(1) .img-fluid")).click()
    await driver.findElement(By.id("add-review")).click()
    await driver.findElement(By.id("review-title")).click()
    await driver.findElement(By.id("review-title")).sendKeys("\'\'")
    await driver.findElement(By.id("review-description")).click()
    await driver.findElement(By.id("review-description")).sendKeys("Producto en excelente estado. ")
    await driver.findElement(By.id("review-rating")).click()
    await driver.findElement(By.id("review-rating")).sendKeys("5")
    await driver.findElement(By.id("addReview")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Please supply a review title")
  })
})