// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search-ci-empty', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search-ci-empty', async function() {
    await driver.get("http://localhost:1111/")
    await driver.manage().window().setRect({ width: 1366, height: 736 })
    await driver.findElement(By.id("frm_search")).click()
    await driver.findElement(By.id("frm_search")).sendKeys("")
    await driver.findElement(By.id("frm_search")).sendKeys(Key.ENTER)
    assert(await driver.findElement(By.css(".col-sm-12 > .text-danger")).getText() == "the Product title field is required")
    await driver.sleep(5000)
  })
})


describe('search-ci-dont-exist', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search-ci-dont-exist', async function() {
    await driver.get("http://localhost:1111/")
    await driver.manage().window().setRect({ width: 1366, height: 736 })
    await driver.findElement(By.id("frm_search")).click()
    await driver.findElement(By.id("frm_search")).sendKeys("Carro")
    await driver.findElement(By.id("frm_search")).sendKeys(Key.ENTER)
    assert(await driver.findElement(By.css(".col-sm-12 > .text-danger")).getText() == "No products found")
    await driver.sleep(5000)
  })
})


describe('search-cv', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search-cv', async function() {
    await driver.get("http://localhost:1111/")
    await driver.manage().window().setRect({ width: 1366, height: 736 })
    await driver.findElement(By.id("frm_search")).click()
    await driver.findElement(By.id("frm_search")).sendKeys("jacket")
    await driver.findElement(By.id("frm_search")).sendKeys(Key.ENTER)
    await driver.wait(until.elementLocated(By.css(".product-title")), 30000)
    await driver.sleep(5000)
  })
})