// const {By, Key, Builder} = require('selenium-webdriver');
// require('geckodriver');

// async function example() {
//   let driver = await new Builder().forBrowser('firefox').build();

//   await driver.get('http://www.google.com');

//   await driver.findElement(By.name('q')).sendKeys('webdriver', Key.RETURN);
  
//   setInterval(function () {
//     driver.quit();
//   }, 3000)

// }

// example()

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  }, 30000)
  it('search', async function() {
    await driver.get("http://localhost:1111/")
    await driver.manage().window().setRect({ width: 1366, height: 736 })
    await driver.findElement(By.id("frm_search")).click()
    await driver.sleep(1000);
    await driver.findElement(By.id("frm_search")).sendKeys("jacket")
    await driver.findElement(By.id("frm_search")).sendKeys(Key.ENTER)
    await driver.wait(until.elementLocated(By.css(".product-title")), 30000)
    await driver.sleep(5000);
  })
})