// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('discount_codes', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CI_DISCOUNT_CODE_EMPTY', async function() {
    await driver.get("http://localhost:1111/admin/dashboard")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Discount codes")).click()
    await driver.findElement(By.css(".col-md-12")).click()
    await driver.findElement(By.linkText("New Discount")).click()
    await driver.findElement(By.id("discountCode")).click()
    await driver.findElement(By.id("discountCode")).sendKeys("\\n")
    await driver.findElement(By.id("discountType")).click()
    await driver.findElement(By.id("discountValue")).click()
    await driver.findElement(By.id("discountValue")).sendKeys("20")
    {
      const element = await driver.findElement(By.id("discountStart"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(19)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(6) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(19) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(7) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(20) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
  })
  it('CI_DISCOUNT_END_EMPTY', async function() {
    await driver.get("http://localhost:1111/admin/dashboard")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Discount codes")).click()
    await driver.findElement(By.linkText("New Discount")).click()
    await driver.findElement(By.id("discountCode")).click()
    await driver.findElement(By.id("discountCode")).sendKeys("CODE23")
    await driver.findElement(By.id("discountType")).click()
    await driver.findElement(By.css(".col-12:nth-child(4) > .form-group")).click()
    await driver.findElement(By.id("discountValue")).click()
    await driver.findElement(By.id("discountValue")).sendKeys("20")
    {
      const element = await driver.findElement(By.id("discountStart"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(19)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(6) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(19) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    await driver.findElement(By.id("notify_message")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "A end date must be entered")
  })
  it('CI_DISCOUNT_START _EMPTY', async function() {
    await driver.get("http://localhost:1111/admin/dashboard")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Discount codes")).click()
    await driver.findElement(By.linkText("New Discount")).click()
    await driver.findElement(By.id("discountCode")).click()
    await driver.findElement(By.id("discountCode")).sendKeys("CODE20")
    await driver.findElement(By.id("discountType")).click()
    await driver.findElement(By.id("discountNewForm")).click()
    await driver.findElement(By.id("discountValue")).click()
    await driver.findElement(By.id("discountValue")).sendKeys("20")
    {
      const element = await driver.findElement(By.id("discountStart"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(19)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(4) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(19) .btn:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.id("discountEnd"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(20)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(6) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(20) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Discount start date needs to be after today")
  })
  it('CI_DISCOUNT_VALUE_EMPTY', async function() {
    await driver.get("http://localhost:1111/admin/dashboard")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Discount codes")).click()
    await driver.findElement(By.css(".col-md-12")).click()
    await driver.findElement(By.linkText("New Discount")).click()
    await driver.findElement(By.id("discountCode")).click()
    await driver.findElement(By.id("discountCode")).sendKeys("CODE2")
    await driver.findElement(By.id("discountType")).click()
    await driver.findElement(By.id("discountValue")).click()
    await driver.findElement(By.id("discountValue")).sendKeys("\\n")
    {
      const element = await driver.findElement(By.id("discountStart"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(19)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(6) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(19) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(7) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(20) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
  })
  it('CI_INVALID_DISCOUNT_CODE', async function() {
    await driver.get("http://localhost:1111/admin/dashboard")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Discount codes")).click()
    await driver.findElement(By.css(".col-md-12")).click()
    await driver.findElement(By.linkText("New Discount")).click()
    await driver.findElement(By.id("discountCode")).click()
    await driver.findElement(By.id("discountCode")).sendKeys("CO")
    await driver.findElement(By.id("discountType")).click()
    await driver.findElement(By.id("discountValue")).click()
    await driver.findElement(By.id("discountValue")).sendKeys("20")
    {
      const element = await driver.findElement(By.id("discountStart"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(19)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(6) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(19) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(7) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(20) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Invalid discount code")
  })
  it('CI_INVALID_DISCOUNT_END', async function() {
    await driver.get("http://localhost:1111/admin/dashboard")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Discount codes")).click()
    await driver.findElement(By.linkText("New Discount")).click()
    await driver.findElement(By.css(".col-12:nth-child(2) > .form-group")).click()
    await driver.findElement(By.id("discountCode")).click()
    await driver.findElement(By.id("discountCode")).sendKeys("CODE23")
    await driver.findElement(By.id("discountType")).click()
    await driver.findElement(By.id("discountValue")).click()
    await driver.findElement(By.id("discountValue")).sendKeys("20")
    {
      const element = await driver.findElement(By.id("discountStart"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(19)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(6) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(19) .btn:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.id("discountEnd"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(20)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(2) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(20) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Discount end date needs to be after start date")
  })
  it('CI_INVALID_DISCOUNT_START', async function() {
    await driver.get("http://localhost:1111/admin/dashboard")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Discount codes")).click()
    await driver.findElement(By.linkText("New Discount")).click()
    await driver.findElement(By.id("discountCode")).click()
    await driver.findElement(By.id("discountCode")).sendKeys("CODE23")
    await driver.findElement(By.id("discountType")).click()
    await driver.findElement(By.id("discountValue")).click()
    await driver.findElement(By.id("discountValue")).sendKeys("20")
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(6) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(20) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "A start date must be entered")
  })
  it('CI_INVALID_DISCOUNT_VALUE', async function() {
    await driver.get("http://localhost:1111/admin/dashboard")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Discount codes")).click()
    await driver.findElement(By.css(".col-md-12")).click()
    await driver.findElement(By.linkText("New Discount")).click()
    await driver.findElement(By.id("discountCode")).click()
    await driver.findElement(By.id("discountCode")).sendKeys("CODE2")
    await driver.findElement(By.id("discountType")).click()
    await driver.findElement(By.id("discountValue")).click()
    await driver.findElement(By.id("discountValue")).sendKeys("20.5")
    {
      const element = await driver.findElement(By.id("discountStart"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(19)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(6) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(19) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(7) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(20) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
  })
  it('CV', async function() {
    await driver.get("http://localhost:1111/admin/dashboard")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Discount codes")).click()
    await driver.findElement(By.css(".col-md-12")).click()
    await driver.findElement(By.linkText("New Discount")).click()
    await driver.findElement(By.id("discountCode")).click()
    await driver.findElement(By.id("discountCode")).sendKeys("CODE")
    await driver.findElement(By.id("discountType")).click()
    await driver.findElement(By.id("discountValue")).click()
    await driver.findElement(By.id("discountValue")).sendKeys("20")
    {
      const element = await driver.findElement(By.id("discountStart"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".gj-modal:nth-child(19)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(6) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(19) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".admin")).click()
    await driver.findElement(By.css("tr:nth-child(4) > .current-month:nth-child(7) > div")).click()
    await driver.findElement(By.css(".gj-modal:nth-child(20) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn-outline-success:nth-child(1)")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Discount code created successfully")
  })
})
