// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SEARCH_REVIEWS', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CI_NO_FOUND', async function() {
    await driver.get("http://localhost:1111/admin/login")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.id("email")).sendKeys("fnarvaez@correo.com")
    await driver.findElement(By.id("password")).sendKeys("tps-pwd07*")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin1@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("admin1")
    await driver.findElement(By.id("loginForm")).click()
    await driver.findElement(By.linkText("Reviews")).click()
    await driver.findElement(By.id("review_filter")).click()
    await driver.findElement(By.id("review_filter")).sendKeys("Carro")
    await driver.findElement(By.id("btn_review_filter")).click()
    await driver.findElement(By.id("container")).click()
    assert(await driver.findElement(By.css(".text-center")).getText() == "There are no reviews")
  })
  it('CV', async function() {
    await driver.get("http://localhost:1111/admin/login")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.id("email")).sendKeys("fnarvaez@correo.com")
    await driver.findElement(By.id("password")).sendKeys("tps-pwd07*")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin1@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("admin1")
    await driver.findElement(By.id("loginForm")).click()
    await driver.findElement(By.linkText("Reviews")).click()
    await driver.findElement(By.id("review_filter")).click()
    await driver.findElement(By.id("review_filter")).sendKeys("Mal producto")
    await driver.findElement(By.id("btn_review_filter")).click()
    await driver.findElement(By.id("container")).click()
    assert(await driver.findElement(By.css(".col-md-5 > .top-pad-8")).getText() == "Mal producto")
  })
  it('CI_EMPTY', async function() {
    await driver.get("http://localhost:1111/admin/login")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.id("email")).sendKeys("fnarvaez@correo.com")
    await driver.findElement(By.id("password")).sendKeys("tps-pwd07*")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin1@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("admin1")
    await driver.findElement(By.id("loginForm")).click()
    await driver.findElement(By.linkText("Reviews")).click()
    await driver.findElement(By.id("review_filter")).click()
    await driver.findElement(By.id("review_filter")).sendKeys("\\n")
    await driver.findElement(By.id("btn_review_filter")).click()
    await driver.findElement(By.id("container")).click()
    assert(await driver.findElement(By.id("notify_message")).getText() == "Please enter a keyword to filter")
  })
})
